### ISSUE TITLE
Add support for usernameless users

### ISSUE THREAD

**Issue by Intervencion** [everyone-bot/everyone-bot#12]
Since months ago Telegram API allows mention of users with no username. I'd like to have support for that on the bot.

**Comment by sla-te** [comment]
me too

**Comment by nate2014jatc** [comment]
This would be a really good feature to have.

**Comment by aquibm** [comment]
There's probably some metadata we can lift off the messages, I'm currently trying to figure out all the enhancements that people are asking for, will get into this one when I can :)

**Comment by aquibm** [comment]
This should now be live :)
