### ISSUE TITLE
Reduce spam by cleaning up after mention messages

### ISSUE THREAD

**Issue by aquibm** [everyone-bot/everyone-bot#13]
We could possibly use the [deleteMessage](https://telegraf.js.org/#/?id=deletemessage) API to remove all of the mention messages and reduce spam in larger groups.

**Comment by nate2014jatc** [comment]
Can we make this configurable? It's disjointing to be mentioned and then see the messages just disappear.

**Comment by microtechton** [comment]
I would like to bump this too

**Comment by aquibm** [comment]
I've just rolled this back out of the codebase because the implementation was never really any good. I disabled it only a few minutes after launch so it shouldn't have impacted anyone.
