### ISSUE TITLE
Admin configurable per-group opt-out setting

### ISSUE THREAD

**Issue by JuniorJPDJ** [everyone-bot/everyone-bot#40]
For me it would be better for everyone to be opt-out not opt-in, but I'm taking in account that bot could be added to group by unprivileged user.

It would be super-cool to be able to set bot to opt-out mode in group.
By default everyone would get tagged and they could opt-out using normal commands.

**Comment by aquibm** [comment]
Unfortunately, telegram doesn't allow this to happen as bots cannot see who is in the group until they directly interact with the bot. It's a privacy feature.

**Comment by JuniorJPDJ** [comment]
You possibly could follow the conversation and automagically add new talking people to the list of group.
Bot would need access to the messages tho.
