### ISSUE TITLE
[Feature] Add a message at the end of mentions

### ISSUE THREAD

**Issue by damiandecurgez** [everyone-bot/everyone-bot#7]
Would be great, if possible, to add a message at the end of mentions so the notification include it and to write all in the same message. For example:

Me:
```/everyone MY MESSAGE```

Everyone:
```@member1 @member2 @member3 @member4 MY MESSAGE```

Great bot, by the way. ;)

**Comment by aquibm** [comment]
That's a really good idea, will look at implementing it this weekend.

**Comment by aquibm** [comment]
@damiandecurgez You should be able to use this now. Also fixed a bunch of reliability issues by switching out to a better supported framework. The old one hadn't been updated in two years :/

**Comment by damiandecurgez** [comment]
Great! Thanks.
